//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoDb.VisualStudio.DataTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuoDb.VisualStudio.DataTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string DataView_Category_DataType {
            get {
                return ResourceManager.GetString("DataView_Category_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Identifier).
        /// </summary>
        internal static string DataView_Category_Identifier {
            get {
                return ResourceManager.GetString("DataView_Category_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc..
        /// </summary>
        internal static string DataView_Category_Misc {
            get {
                return ResourceManager.GetString("DataView_Category_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length (in characters) that can be stored in this database object..
        /// </summary>
        internal static string DataView_Description_Length {
            get {
                return ResourceManager.GetString("DataView_Description_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the database object..
        /// </summary>
        internal static string DataView_Description_Name {
            get {
                return ResourceManager.GetString("DataView_Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if null values are allowed in this database object..
        /// </summary>
        internal static string DataView_Description_Nullable {
            get {
                return ResourceManager.GetString("DataView_Description_Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position of this object in the parent database object definition..
        /// </summary>
        internal static string DataView_Description_Ordinal {
            get {
                return ResourceManager.GetString("DataView_Description_Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For numeric data, the maximum number of decimal digits that can be stored in this database object..
        /// </summary>
        internal static string DataView_Description_Precision {
            get {
                return ResourceManager.GetString("DataView_Description_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For numeric data, the maximum number of decimal digits that can be stored in this database object to the right of a decimal point..
        /// </summary>
        internal static string DataView_Description_Scale {
            get {
                return ResourceManager.GetString("DataView_Description_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema that contains the database object..
        /// </summary>
        internal static string DataView_Description_Schema {
            get {
                return ResourceManager.GetString("DataView_Description_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native NuoDB Server data type..
        /// </summary>
        internal static string DataView_Description_SystemType {
            get {
                return ResourceManager.GetString("DataView_Description_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table that owns this database object..
        /// </summary>
        internal static string DataView_Description_Table {
            get {
                return ResourceManager.GetString("DataView_Description_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value of the database object..
        /// </summary>
        internal static string DataView_Descriptor_Default {
            get {
                return ResourceManager.GetString("DataView_Descriptor_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        internal static string DataView_Node_StoredProcedures {
            get {
                return ResourceManager.GetString("DataView_Node_StoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string DataView_Node_Tables {
            get {
                return ResourceManager.GetString("DataView_Node_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string DataView_Property_Default {
            get {
                return ResourceManager.GetString("DataView_Property_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string DataView_Property_Length {
            get {
                return ResourceManager.GetString("DataView_Property_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Name).
        /// </summary>
        internal static string DataView_Property_Name {
            get {
                return ResourceManager.GetString("DataView_Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Nullable.
        /// </summary>
        internal static string DataView_Property_Nullable {
            get {
                return ResourceManager.GetString("DataView_Property_Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ordinal).
        /// </summary>
        internal static string DataView_Property_Ordinal {
            get {
                return ResourceManager.GetString("DataView_Property_Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        internal static string DataView_Property_Precision {
            get {
                return ResourceManager.GetString("DataView_Property_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string DataView_Property_Scale {
            get {
                return ResourceManager.GetString("DataView_Property_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Schema).
        /// </summary>
        internal static string DataView_Property_Schema {
            get {
                return ResourceManager.GetString("DataView_Property_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Type.
        /// </summary>
        internal static string DataView_Property_SystemType {
            get {
                return ResourceManager.GetString("DataView_Property_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Table).
        /// </summary>
        internal static string DataView_Property_Table {
            get {
                return ResourceManager.GetString("DataView_Property_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Type.
        /// </summary>
        internal static string DataView_Property_TableType {
            get {
                return ResourceManager.GetString("DataView_Property_TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string DataView_Type_Table {
            get {
                return ResourceManager.GetString("DataView_Type_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column.
        /// </summary>
        internal static string DataView_Type_TableColumn {
            get {
                return ResourceManager.GetString("DataView_Type_TableColumn", resourceCulture);
            }
        }
    }
}
