//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("testModel", "PLAYERSSCORING", "PLAYERS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsSample.PLAYERS), "SCORING", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsSample.SCORING))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("testModel", "TEAMSSCORING", "TEAMS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsSample.TEAMS), "SCORING", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsSample.SCORING))]

// Original file name:
// Generation date: 10/12/2023 5:19:01 PM
namespace WindowsFormsSample
{
    
    /// <summary>
    /// There are no comments for testEntities in the schema.
    /// </summary>
    public partial class testEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new testEntities object using the connection string found in the 'testEntities' section of the application configuration file.
        /// </summary>
        public testEntities() : 
                base("name=testEntities", "testEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(string connectionString) : 
                base(connectionString, "testEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "testEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for PLAYERS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PLAYERS> PLAYERS
        {
            get
            {
                if ((this._PLAYERS == null))
                {
                    this._PLAYERS = base.CreateQuery<PLAYERS>("[PLAYERS]");
                }
                return this._PLAYERS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PLAYERS> _PLAYERS;
        /// <summary>
        /// There are no comments for SCORING in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SCORING> SCORING
        {
            get
            {
                if ((this._SCORING == null))
                {
                    this._SCORING = base.CreateQuery<SCORING>("[SCORING]");
                }
                return this._SCORING;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SCORING> _SCORING;
        /// <summary>
        /// There are no comments for TEAMS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<TEAMS> TEAMS
        {
            get
            {
                if ((this._TEAMS == null))
                {
                    this._TEAMS = base.CreateQuery<TEAMS>("[TEAMS]");
                }
                return this._TEAMS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<TEAMS> _TEAMS;
        /// <summary>
        /// There are no comments for PLAYERS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPLAYERS(PLAYERS pLAYERS)
        {
            base.AddObject("PLAYERS", pLAYERS);
        }
        /// <summary>
        /// There are no comments for SCORING in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSCORING(SCORING sCORING)
        {
            base.AddObject("SCORING", sCORING);
        }
        /// <summary>
        /// There are no comments for TEAMS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTEAMS(TEAMS tEAMS)
        {
            base.AddObject("TEAMS", tEAMS);
        }
    }
    /// <summary>
    /// There are no comments for testModel.PLAYERS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PLAYERID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="testModel", Name="PLAYERS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PLAYERS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PLAYERS object.
        /// </summary>
        /// <param name="pLAYERID">Initial value of PLAYERID.</param>
        /// <param name="fIRSTNHL">Initial value of FIRSTNHL.</param>
        /// <param name="lASTNHL">Initial value of LASTNHL.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PLAYERS CreatePLAYERS(string pLAYERID, int fIRSTNHL, int lASTNHL)
        {
            PLAYERS pLAYERS = new PLAYERS();
            pLAYERS.PLAYERID = pLAYERID;
            pLAYERS.FIRSTNHL = fIRSTNHL;
            pLAYERS.LASTNHL = lASTNHL;
            return pLAYERS;
        }
        /// <summary>
        /// There are no comments for property PLAYERID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PLAYERID
        {
            get
            {
                return this._PLAYERID;
            }
            set
            {
                this.OnPLAYERIDChanging(value);
                this.ReportPropertyChanging("PLAYERID");
                this._PLAYERID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PLAYERID");
                this.OnPLAYERIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PLAYERID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPLAYERIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPLAYERIDChanged();
        /// <summary>
        /// There are no comments for property FIRSTNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string FIRSTNAME
        {
            get
            {
                return this._FIRSTNAME;
            }
            set
            {
                this.OnFIRSTNAMEChanging(value);
                this.ReportPropertyChanging("FIRSTNAME");
                this._FIRSTNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FIRSTNAME");
                this.OnFIRSTNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _FIRSTNAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFIRSTNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFIRSTNAMEChanged();
        /// <summary>
        /// There are no comments for property LASTNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string LASTNAME
        {
            get
            {
                return this._LASTNAME;
            }
            set
            {
                this.OnLASTNAMEChanging(value);
                this.ReportPropertyChanging("LASTNAME");
                this._LASTNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LASTNAME");
                this.OnLASTNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _LASTNAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLASTNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLASTNAMEChanged();
        /// <summary>
        /// There are no comments for property HEIGHT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> HEIGHT
        {
            get
            {
                return this._HEIGHT;
            }
            set
            {
                this.OnHEIGHTChanging(value);
                this.ReportPropertyChanging("HEIGHT");
                this._HEIGHT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HEIGHT");
                this.OnHEIGHTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _HEIGHT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnHEIGHTChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnHEIGHTChanged();
        /// <summary>
        /// There are no comments for property WEIGHT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> WEIGHT
        {
            get
            {
                return this._WEIGHT;
            }
            set
            {
                this.OnWEIGHTChanging(value);
                this.ReportPropertyChanging("WEIGHT");
                this._WEIGHT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WEIGHT");
                this.OnWEIGHTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _WEIGHT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnWEIGHTChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnWEIGHTChanged();
        /// <summary>
        /// There are no comments for property FIRSTNHL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int FIRSTNHL
        {
            get
            {
                return this._FIRSTNHL;
            }
            set
            {
                this.OnFIRSTNHLChanging(value);
                this.ReportPropertyChanging("FIRSTNHL");
                this._FIRSTNHL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FIRSTNHL");
                this.OnFIRSTNHLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _FIRSTNHL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFIRSTNHLChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFIRSTNHLChanged();
        /// <summary>
        /// There are no comments for property LASTNHL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int LASTNHL
        {
            get
            {
                return this._LASTNHL;
            }
            set
            {
                this.OnLASTNHLChanging(value);
                this.ReportPropertyChanging("LASTNHL");
                this._LASTNHL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LASTNHL");
                this.OnLASTNHLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _LASTNHL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLASTNHLChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLASTNHLChanged();
        /// <summary>
        /// There are no comments for property POSITION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string POSITION
        {
            get
            {
                return this._POSITION;
            }
            set
            {
                this.OnPOSITIONChanging(value);
                this.ReportPropertyChanging("POSITION");
                this._POSITION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("POSITION");
                this.OnPOSITIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _POSITION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPOSITIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPOSITIONChanged();
        /// <summary>
        /// There are no comments for property BIRTHYEAR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> BIRTHYEAR
        {
            get
            {
                return this._BIRTHYEAR;
            }
            set
            {
                this.OnBIRTHYEARChanging(value);
                this.ReportPropertyChanging("BIRTHYEAR");
                this._BIRTHYEAR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BIRTHYEAR");
                this.OnBIRTHYEARChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _BIRTHYEAR;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHYEARChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHYEARChanged();
        /// <summary>
        /// There are no comments for property BIRTHMON in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> BIRTHMON
        {
            get
            {
                return this._BIRTHMON;
            }
            set
            {
                this.OnBIRTHMONChanging(value);
                this.ReportPropertyChanging("BIRTHMON");
                this._BIRTHMON = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BIRTHMON");
                this.OnBIRTHMONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _BIRTHMON;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHMONChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHMONChanged();
        /// <summary>
        /// There are no comments for property BIRTHDAY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> BIRTHDAY
        {
            get
            {
                return this._BIRTHDAY;
            }
            set
            {
                this.OnBIRTHDAYChanging(value);
                this.ReportPropertyChanging("BIRTHDAY");
                this._BIRTHDAY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BIRTHDAY");
                this.OnBIRTHDAYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _BIRTHDAY;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHDAYChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHDAYChanged();
        /// <summary>
        /// There are no comments for property BIRTHCOUNTRY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string BIRTHCOUNTRY
        {
            get
            {
                return this._BIRTHCOUNTRY;
            }
            set
            {
                this.OnBIRTHCOUNTRYChanging(value);
                this.ReportPropertyChanging("BIRTHCOUNTRY");
                this._BIRTHCOUNTRY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BIRTHCOUNTRY");
                this.OnBIRTHCOUNTRYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _BIRTHCOUNTRY;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHCOUNTRYChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHCOUNTRYChanged();
        /// <summary>
        /// There are no comments for property BIRTHSTATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string BIRTHSTATE
        {
            get
            {
                return this._BIRTHSTATE;
            }
            set
            {
                this.OnBIRTHSTATEChanging(value);
                this.ReportPropertyChanging("BIRTHSTATE");
                this._BIRTHSTATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BIRTHSTATE");
                this.OnBIRTHSTATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _BIRTHSTATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHSTATEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHSTATEChanged();
        /// <summary>
        /// There are no comments for property BIRTHCITY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string BIRTHCITY
        {
            get
            {
                return this._BIRTHCITY;
            }
            set
            {
                this.OnBIRTHCITYChanging(value);
                this.ReportPropertyChanging("BIRTHCITY");
                this._BIRTHCITY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BIRTHCITY");
                this.OnBIRTHCITYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _BIRTHCITY;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHCITYChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBIRTHCITYChanged();
        /// <summary>
        /// There are no comments for SCORING in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("testModel", "PLAYERSSCORING", "SCORING")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SCORING> SCORING
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SCORING>("testModel.PLAYERSSCORING", "SCORING");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SCORING>("testModel.PLAYERSSCORING", "SCORING", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for testModel.SCORING in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PLAYERID
    /// YEAR
    /// STINT
    /// TEAMID
    /// POSITION
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="testModel", Name="SCORING")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SCORING : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SCORING object.
        /// </summary>
        /// <param name="pLAYERID">Initial value of PLAYERID.</param>
        /// <param name="yEAR">Initial value of YEAR.</param>
        /// <param name="sTINT">Initial value of STINT.</param>
        /// <param name="tEAMID">Initial value of TEAMID.</param>
        /// <param name="pOSITION">Initial value of POSITION.</param>
        /// <param name="gAMESPLAYED">Initial value of GAMESPLAYED.</param>
        /// <param name="gOALS">Initial value of GOALS.</param>
        /// <param name="aSSISTS">Initial value of ASSISTS.</param>
        /// <param name="pENALTYMINUTES">Initial value of PENALTYMINUTES.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SCORING CreateSCORING(string pLAYERID, int yEAR, int sTINT, string tEAMID, string pOSITION, int gAMESPLAYED, int gOALS, int aSSISTS, int pENALTYMINUTES)
        {
            SCORING sCORING = new SCORING();
            sCORING.PLAYERID = pLAYERID;
            sCORING.YEAR = yEAR;
            sCORING.STINT = sTINT;
            sCORING.TEAMID = tEAMID;
            sCORING.POSITION = pOSITION;
            sCORING.GAMESPLAYED = gAMESPLAYED;
            sCORING.GOALS = gOALS;
            sCORING.ASSISTS = aSSISTS;
            sCORING.PENALTYMINUTES = pENALTYMINUTES;
            return sCORING;
        }
        /// <summary>
        /// There are no comments for property PLAYERID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PLAYERID
        {
            get
            {
                return this._PLAYERID;
            }
            set
            {
                this.OnPLAYERIDChanging(value);
                this.ReportPropertyChanging("PLAYERID");
                this._PLAYERID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PLAYERID");
                this.OnPLAYERIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PLAYERID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPLAYERIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPLAYERIDChanged();
        /// <summary>
        /// There are no comments for property YEAR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int YEAR
        {
            get
            {
                return this._YEAR;
            }
            set
            {
                this.OnYEARChanging(value);
                this.ReportPropertyChanging("YEAR");
                this._YEAR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("YEAR");
                this.OnYEARChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _YEAR;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnYEARChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnYEARChanged();
        /// <summary>
        /// There are no comments for property STINT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int STINT
        {
            get
            {
                return this._STINT;
            }
            set
            {
                this.OnSTINTChanging(value);
                this.ReportPropertyChanging("STINT");
                this._STINT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("STINT");
                this.OnSTINTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _STINT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSTINTChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSTINTChanged();
        /// <summary>
        /// There are no comments for property TEAMID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TEAMID
        {
            get
            {
                return this._TEAMID;
            }
            set
            {
                this.OnTEAMIDChanging(value);
                this.ReportPropertyChanging("TEAMID");
                this._TEAMID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TEAMID");
                this.OnTEAMIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TEAMID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTEAMIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTEAMIDChanged();
        /// <summary>
        /// There are no comments for property POSITION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string POSITION
        {
            get
            {
                return this._POSITION;
            }
            set
            {
                this.OnPOSITIONChanging(value);
                this.ReportPropertyChanging("POSITION");
                this._POSITION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("POSITION");
                this.OnPOSITIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _POSITION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPOSITIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPOSITIONChanged();
        /// <summary>
        /// There are no comments for property GAMESPLAYED in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int GAMESPLAYED
        {
            get
            {
                return this._GAMESPLAYED;
            }
            set
            {
                this.OnGAMESPLAYEDChanging(value);
                this.ReportPropertyChanging("GAMESPLAYED");
                this._GAMESPLAYED = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GAMESPLAYED");
                this.OnGAMESPLAYEDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _GAMESPLAYED;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGAMESPLAYEDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGAMESPLAYEDChanged();
        /// <summary>
        /// There are no comments for property GOALS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int GOALS
        {
            get
            {
                return this._GOALS;
            }
            set
            {
                this.OnGOALSChanging(value);
                this.ReportPropertyChanging("GOALS");
                this._GOALS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GOALS");
                this.OnGOALSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _GOALS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGOALSChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGOALSChanged();
        /// <summary>
        /// There are no comments for property ASSISTS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ASSISTS
        {
            get
            {
                return this._ASSISTS;
            }
            set
            {
                this.OnASSISTSChanging(value);
                this.ReportPropertyChanging("ASSISTS");
                this._ASSISTS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ASSISTS");
                this.OnASSISTSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ASSISTS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnASSISTSChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnASSISTSChanged();
        /// <summary>
        /// There are no comments for property PENALTYMINUTES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int PENALTYMINUTES
        {
            get
            {
                return this._PENALTYMINUTES;
            }
            set
            {
                this.OnPENALTYMINUTESChanging(value);
                this.ReportPropertyChanging("PENALTYMINUTES");
                this._PENALTYMINUTES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PENALTYMINUTES");
                this.OnPENALTYMINUTESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _PENALTYMINUTES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPENALTYMINUTESChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPENALTYMINUTESChanged();
        /// <summary>
        /// There are no comments for PLAYERS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("testModel", "PLAYERSSCORING", "PLAYERS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PLAYERS PLAYERS
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PLAYERS>("testModel.PLAYERSSCORING", "PLAYERS").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PLAYERS>("testModel.PLAYERSSCORING", "PLAYERS").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PLAYERS in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PLAYERS> PLAYERSReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PLAYERS>("testModel.PLAYERSSCORING", "PLAYERS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PLAYERS>("testModel.PLAYERSSCORING", "PLAYERS", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TEAMS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("testModel", "TEAMSSCORING", "TEAMS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TEAMS TEAMS
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TEAMS>("testModel.TEAMSSCORING", "TEAMS").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TEAMS>("testModel.TEAMSSCORING", "TEAMS").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TEAMS in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TEAMS> TEAMSReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TEAMS>("testModel.TEAMSSCORING", "TEAMS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TEAMS>("testModel.TEAMSSCORING", "TEAMS", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for testModel.TEAMS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// YEAR
    /// TEAMID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="testModel", Name="TEAMS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TEAMS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TEAMS object.
        /// </summary>
        /// <param name="yEAR">Initial value of YEAR.</param>
        /// <param name="tEAMID">Initial value of TEAMID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        /// <param name="cONFERENCEID">Initial value of CONFERENCEID.</param>
        /// <param name="dIVISIONID">Initial value of DIVISIONID.</param>
        /// <param name="rANK">Initial value of RANK.</param>
        /// <param name="pLAYOFF">Initial value of PLAYOFF.</param>
        /// <param name="gAMES">Initial value of GAMES.</param>
        /// <param name="wINS">Initial value of WINS.</param>
        /// <param name="lOSSES">Initial value of LOSSES.</param>
        /// <param name="tIES">Initial value of TIES.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static TEAMS CreateTEAMS(int yEAR, string tEAMID, string nAME, string cONFERENCEID, string dIVISIONID, int rANK, string pLAYOFF, int gAMES, int wINS, int lOSSES, int tIES)
        {
            TEAMS tEAMS = new TEAMS();
            tEAMS.YEAR = yEAR;
            tEAMS.TEAMID = tEAMID;
            tEAMS.NAME = nAME;
            tEAMS.CONFERENCEID = cONFERENCEID;
            tEAMS.DIVISIONID = dIVISIONID;
            tEAMS.RANK = rANK;
            tEAMS.PLAYOFF = pLAYOFF;
            tEAMS.GAMES = gAMES;
            tEAMS.WINS = wINS;
            tEAMS.LOSSES = lOSSES;
            tEAMS.TIES = tIES;
            return tEAMS;
        }
        /// <summary>
        /// There are no comments for property YEAR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int YEAR
        {
            get
            {
                return this._YEAR;
            }
            set
            {
                this.OnYEARChanging(value);
                this.ReportPropertyChanging("YEAR");
                this._YEAR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("YEAR");
                this.OnYEARChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _YEAR;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnYEARChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnYEARChanged();
        /// <summary>
        /// There are no comments for property TEAMID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TEAMID
        {
            get
            {
                return this._TEAMID;
            }
            set
            {
                this.OnTEAMIDChanging(value);
                this.ReportPropertyChanging("TEAMID");
                this._TEAMID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TEAMID");
                this.OnTEAMIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TEAMID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTEAMIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTEAMIDChanged();
        /// <summary>
        /// There are no comments for property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for property CONFERENCEID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CONFERENCEID
        {
            get
            {
                return this._CONFERENCEID;
            }
            set
            {
                this.OnCONFERENCEIDChanging(value);
                this.ReportPropertyChanging("CONFERENCEID");
                this._CONFERENCEID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CONFERENCEID");
                this.OnCONFERENCEIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CONFERENCEID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCONFERENCEIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCONFERENCEIDChanged();
        /// <summary>
        /// There are no comments for property DIVISIONID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DIVISIONID
        {
            get
            {
                return this._DIVISIONID;
            }
            set
            {
                this.OnDIVISIONIDChanging(value);
                this.ReportPropertyChanging("DIVISIONID");
                this._DIVISIONID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DIVISIONID");
                this.OnDIVISIONIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DIVISIONID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDIVISIONIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDIVISIONIDChanged();
        /// <summary>
        /// There are no comments for property RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int RANK
        {
            get
            {
                return this._RANK;
            }
            set
            {
                this.OnRANKChanging(value);
                this.ReportPropertyChanging("RANK");
                this._RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RANK");
                this.OnRANKChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _RANK;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRANKChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRANKChanged();
        /// <summary>
        /// There are no comments for property PLAYOFF in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PLAYOFF
        {
            get
            {
                return this._PLAYOFF;
            }
            set
            {
                this.OnPLAYOFFChanging(value);
                this.ReportPropertyChanging("PLAYOFF");
                this._PLAYOFF = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PLAYOFF");
                this.OnPLAYOFFChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PLAYOFF;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPLAYOFFChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPLAYOFFChanged();
        /// <summary>
        /// There are no comments for property GAMES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int GAMES
        {
            get
            {
                return this._GAMES;
            }
            set
            {
                this.OnGAMESChanging(value);
                this.ReportPropertyChanging("GAMES");
                this._GAMES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GAMES");
                this.OnGAMESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _GAMES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGAMESChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGAMESChanged();
        /// <summary>
        /// There are no comments for property WINS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int WINS
        {
            get
            {
                return this._WINS;
            }
            set
            {
                this.OnWINSChanging(value);
                this.ReportPropertyChanging("WINS");
                this._WINS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WINS");
                this.OnWINSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _WINS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnWINSChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnWINSChanged();
        /// <summary>
        /// There are no comments for property LOSSES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int LOSSES
        {
            get
            {
                return this._LOSSES;
            }
            set
            {
                this.OnLOSSESChanging(value);
                this.ReportPropertyChanging("LOSSES");
                this._LOSSES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LOSSES");
                this.OnLOSSESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _LOSSES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLOSSESChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLOSSESChanged();
        /// <summary>
        /// There are no comments for property TIES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TIES
        {
            get
            {
                return this._TIES;
            }
            set
            {
                this.OnTIESChanging(value);
                this.ReportPropertyChanging("TIES");
                this._TIES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TIES");
                this.OnTIESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TIES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTIESChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTIESChanged();
        /// <summary>
        /// There are no comments for property OVERTIMELOSSES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> OVERTIMELOSSES
        {
            get
            {
                return this._OVERTIMELOSSES;
            }
            set
            {
                this.OnOVERTIMELOSSESChanging(value);
                this.ReportPropertyChanging("OVERTIMELOSSES");
                this._OVERTIMELOSSES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OVERTIMELOSSES");
                this.OnOVERTIMELOSSESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _OVERTIMELOSSES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnOVERTIMELOSSESChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnOVERTIMELOSSESChanged();
        /// <summary>
        /// There are no comments for SCORING in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("testModel", "TEAMSSCORING", "SCORING")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SCORING> SCORING
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SCORING>("testModel.TEAMSSCORING", "SCORING");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SCORING>("testModel.TEAMSSCORING", "SCORING", value);
                }
            }
        }
    }
}
