//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WindowsFormsSample
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testEntities object using the connection string found in the 'testEntities' section of the application configuration file.
        /// </summary>
        public testEntities() : base("name=testEntities", "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(string connectionString) : base(connectionString, "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(EntityConnection connection) : base(connection, "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HOCKEY> HOCKEY
        {
            get
            {
                if ((_HOCKEY == null))
                {
                    _HOCKEY = base.CreateObjectSet<HOCKEY>("HOCKEY");
                }
                return _HOCKEY;
            }
        }
        private ObjectSet<HOCKEY> _HOCKEY;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HOCKEY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHOCKEY(HOCKEY hOCKEY)
        {
            base.AddObject("HOCKEY", hOCKEY);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="HOCKEY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HOCKEY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HOCKEY object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static HOCKEY CreateHOCKEY(global::System.Int32 id)
        {
            HOCKEY hOCKEY = new HOCKEY();
            hOCKEY.ID = id;
            return hOCKEY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NUMBER
        {
            get
            {
                return _NUMBER;
            }
            set
            {
                OnNUMBERChanging(value);
                ReportPropertyChanging("NUMBER");
                _NUMBER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUMBER");
                OnNUMBERChanged();
            }
        }
        private Nullable<global::System.Int32> _NUMBER;
        partial void OnNUMBERChanging(Nullable<global::System.Int32> value);
        partial void OnNUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POSITION
        {
            get
            {
                return _POSITION;
            }
            set
            {
                OnPOSITIONChanging(value);
                ReportPropertyChanging("POSITION");
                _POSITION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POSITION");
                OnPOSITIONChanged();
            }
        }
        private global::System.String _POSITION;
        partial void OnPOSITIONChanging(global::System.String value);
        partial void OnPOSITIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEAM
        {
            get
            {
                return _TEAM;
            }
            set
            {
                OnTEAMChanging(value);
                ReportPropertyChanging("TEAM");
                _TEAM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEAM");
                OnTEAMChanged();
            }
        }
        private global::System.String _TEAM;
        partial void OnTEAMChanging(global::System.String value);
        partial void OnTEAMChanged();

        #endregion
    
    }

    #endregion
    
}
